# This is a basic workflow to help you get started with Actions
name: MacOS
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install deps
        run: |
          brew install libsodium
          brew install libtool
          brew install automake
          brew install pkg-config
          brew install libpqxx 

      - name: Build the app    
        run: |
           ./autogen.sh
           ./configure
           export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
           make -j`nproc`
           sudo make install

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: digitalbits-core
          path: /usr/local/bin/digitalbits-core
          retention-days: 5