name: Ubuntu
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y git alien \
                    build-essential pkg-config \
                    autoconf automake libtool \
                    bison flex libpq-dev \
                    libunwind-dev parallel \
                    clang-8 \
                    gcc-6 g++-6 cpp-6 \
                    libc++-8-dev libc++abi-8-dev unzip curl \
                    python3-pip ruby ruby-dev rubygems python3-setuptools
          pip3 install wheel
          pip3 install cloudsmith-cli==0.26.0
          pip3 uninstall click -y
          pip3 install click==7.1.2
          sudo gem install --no-document fpm

      - name: Build the app    
        run: |
          export ENV CC=clang-8
          export ENV CXX=clang++-8
          export ENV CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
          export ENV CXXFLAGS="$CFLAGS -stdlib=libc++" 
           ./autogen.sh
           ./configure  
           make -j`nproc`
           sudo make install
           mkdir /opt/digitalbits
           sudo cp /usr/local/bin/digitalbits-core /opt/digitalbits/digitalbits-core     
      
      - name: Github Tag Bump
        id: bump_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          DEFAULT_BUMP: "patch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false  
          
      - name: Make .deb package
        run: |
            fpm -f -s dir -t deb -n digitalbits-core -v ${{ steps.bump_version.outputs.tag }} --deb-use-file-permissions \
            /opt/digitalbits/digitalbits-core=/usr/local/bin/digitalbits-core \
            digitalbits-core.service=/etc/systemd/system/digitalbits-core.service \
            digitalbits-core=/etc/logrotate.d/digitalbits-core

      - name: Make .rpm package 
        run: | 
          sudo alien -r -k digitalbits-core_${{ steps.bump_version.outputs.tag }}_amd64.deb

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "digitalbits-core*"
          tag: ${{ steps.bump_version.outputs.tag }}
          bodyFile: "README.md"
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}