name: RPM
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y git alien \
                    build-essential pkg-config \
                    autoconf automake libtool \
                    bison flex libpq-dev \
                    libunwind-dev parallel \
                    clang-8 \
                    gcc-6 g++-6 cpp-6 \
                    libc++-8-dev libc++abi-8-dev unzip curl \
                    python3-pip ruby ruby-dev rubygems python3-setuptools
          pip3 install wheel
          pip3 install cloudsmith-cli==0.26.0
          pip3 uninstall click -y
          pip3 install click==7.1.2
          sudo gem install --no-document fpm

      - name: Build the app    
        run: |
          export ENV CC=clang-8
          export ENV CXX=clang++-8
          export ENV CFLAGS="-O3 -g1 -fno-omit-frame-pointer"
          export ENV CXXFLAGS="$CFLAGS -stdlib=libc++" 
           ./autogen.sh
           ./configure  
           make -j`nproc`
           sudo make install
           mkdir /opt/digitalbits
           sudo cp /usr/local/bin/digitalbits-core /opt/digitalbits/digitalbits-core     
               
      - name: Make .deb package
        run: |
            fpm -f -s dir -t deb -n digitalbits-core -v 1.0.0 --deb-use-file-permissions \
            /opt/digitalbits/digitalbits-core=/usr/local/bin/digitalbits-core \
            digitalbits-core.service=/etc/systemd/system/digitalbits-core.service \
            digitalbits-core=/etc/logrotate.d/digitalbits-core
      - name: Make .rpm package
        run: |
          sudo alien -r digitalbits-core_1.0.0_amd64.deb
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: RPM package
          path: digitalbits-core-1.0.0-2.x86_64.rpm
          retention-days: 5